### ISSUE TITLE
Change beamwidth to 1 word

### ISSUE THREAD

**Issue by wkozmaNTIA** [NTIA/sigmf-ns-ntia#22]
In the [Antenna Object](https://github.com/NTIA/sigmf-ns-ntia/blob/master/ntia-core.sigmf-ext.md), the vertical and horizontal beamwidth properties are defined as `..._beam_width`, implying beamwidth is two words.  Beamwidth is one word, and thus is should be `..._beamwidth`.  This effects the Java object as well.

**Comment by dboulware** [comment]
This change was made a while ago.
