### ISSUE TITLE
name should be required in RFPath object

### ISSUE THREAD

**Issue by dboulware** [NTIA/sigmf-ns-ntia#29]
If name is required then we can remove the ambiguity of how to refer to preselector paths and how to interface with the preselector in software. This would simplify the interface to just set_source on the preselector instead of also supporting set_rf_path.

**Comment by aromanielloNTIA** [comment]
Would this be considered a breaking change, since metadata constructed with ntia-sensor v1.0.0 may not have the `name` property in an `RFPath`? Software written to parse metadata which requires `RFPath` objects to have `name` properties would not work for older metadata files missing this field.

**Comment by aromanielloNTIA** [comment]
The `name` is changed to `id` and made a required field in #42 

This issue is resolved and should be closed when it is merged.
