### ISSUE TITLE
`ntia-location` is outdated

### ISSUE THREAD

**Issue by aromanielloNTIA** [NTIA/sigmf-ns-ntia#38]
The `ntia-location` [specification document](https://github.com/NTIA/sigmf-ns-ntia/blob/master/ntia-location.sigmf-ext.md) was last updated in March 2020, when SigMF had only [basic support](https://github.com/sigmf/SigMF/blob/367271953520d4a1ac432cc65328ddf3285dc913/sigmf-spec.md#annotation-segment-objects) for annotating latitude and longitude.

### Upstream SigMF has Improved

SigMF now (v1.0.0) includes better geolocation handling, using [GeoJSON](https://geojson.org/) which is [standardized](https://www.rfc-editor.org/rfc/rfc7946) and commonly supported by software libraries.

The [SigMF v1.0.0 specification](https://github.com/sigmf/SigMF/blob/sigmf-v1.x/sigmf-spec.md#global-object) includes a `core:geolocation` field which uses a GeoJSON `point` object to record latitude, longitude, and altitude. GeoJSON forces adherence to: the WGS84 coordinate system, decimal degrees for latitude and longitude, and  meters above the WGS84 ellipsoid for altitude. WGS84 is the standard coordinate system for GPS.

GeoJSON objects are, similarly to SigMF itself, extensible per [RFC 7946](https://www.rfc-editor.org/rfc/rfc7946) Section 6.1 by adding "foreign member" fields to the object. The SigMF specification now recommends that location-related extensions make use of this:

> Because the SigMF requirement for the `geolocation` field is to be a valid GeoJSON `point` Object, users MAY include _Foreign Member_ fields here for user-defined purposes (position valid indication, GNSS SV counts, dillution of precision, accuracy, etc). It is strongly RECOMMENDED that all fields be documented in a SigMF Extension document.

### How Does `ntia-location` Compare to SigMF v1.0.0

- `ntia-location` provides the following benefits compared to base SigMF:
  - It adds support for _mobile_ recorders/emitters, using the `speed` and `bearing` fields of the [Location object](https://github.com/NTIA/sigmf-ns-ntia/blob/master/ntia-location.sigmf-ext.md#16-location-object), and recording units in the [CoordinateSystem](https://github.com/NTIA/sigmf-ns-ntia/blob/master/ntia-location.sigmf-ext.md#11-coordinatesystem-object) object.
  - It provides flexibility to use a multitude of coordinate systems (though I am unaware of use cases which motivate use of non-WGS84 coordinate systems).
- `ntia-location` is a worse solution than base SigMF in the following ways:
  - Allowing multiple coordinate systems creates a need for much more metadata in order to annotate the coordinate system. The majority of the `ntia-location` specification deals with annotating the use of non-standard coordinate systems or projections. This information requires manual parsing (by a human) prior to post-processing. The diversity of possibilities makes it more difficult to properly integrate `ntia-location` into automated measurement software.
  - It creates a huge level of complication when most applications would simply record standard GPS coordinates.

### What Should Change?

A new definition for `ntia-location` could supplement use of the base SigMF `core:geolocation` field for recording location as a GeoJSON `point` object. In this case, the `ntia-location` extension would become substantially smaller, easier to use, and better standardized (being more in line with SigMF and GPS standards). From a user standpoint, use of any non-WGS84 coordinate systems would need to be handled outside of the metadata. This approach makes SigMF files using `ntia-location` much more machine-readable, by removing the necessity for human intervention to interpret the coordinate system.

If there is interest any changes along these lines, I can draft a new `ntia-location` specification document.

**Comment by MichaelCotton** [comment]
@aromanielloNTIA: Pls propose a new `ntia-location` spec

**Comment by aromanielloNTIA** [comment]
Proceeding with the following approach:
- Non-WGS84 coordinate systems and projections are out-of-scope due to limited use case and preference for using the base SigMF geolocation field. Coordinate system conversions or projections can be performed in the client application if needed.
- `ntia-location` currently allows documentation of sensor or emitter speed, while core SigMF does not. The mobile sensor case will be covered by changes to official SigMF as per https://github.com/sigmf/SigMF/pull/237. This update is still early WIP, so NTIA input can likely be considered for the specifics of the implementation. An update to `ntia-emitter` will follow suit, to use the same approach to record the locations of a mobile emitter.

**Comment by aromanielloNTIA** [comment]
This issue is addressed by #42 and should be closed when it is merged
